"""Dedicated keypair, SSH config include, nodes.json, and SSH reachability."""

from __future__ import annotations

import json
import subprocess
import time
from dataclasses import dataclass
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

from .config import Settings
from .providers.base import NodeInfo


@dataclass(frozen=True)
class Keypair:
    private_path: Path
    public_key: str  # OpenSSH one-liner, no comment


def ensure_keypair(cfg: Settings) -> Keypair:
    priv = cfg.key_path
    pub = priv.with_suffix(".pub")
    if not priv.exists():
        priv.parent.mkdir(parents=True, exist_ok=True)
        key = Ed25519PrivateKey.generate()
        priv.write_bytes(
            key.private_bytes(
                serialization.Encoding.PEM,
                serialization.PrivateFormat.OpenSSH,
                serialization.NoEncryption(),
            )
        )
        priv.chmod(0o600)
        pub.write_bytes(
            key.public_key().public_bytes(
                serialization.Encoding.OpenSSH, serialization.PublicFormat.OpenSSH
            )
        )
    else:
        key = serialization.load_ssh_private_key(priv.read_bytes(), password=None)
        pub.write_bytes(
            key.public_key().public_bytes(
                serialization.Encoding.OpenSSH, serialization.PublicFormat.OpenSSH
            )
        )
    return Keypair(priv.resolve(), pub.read_text().strip())


def existing_or_ephemeral_keypair(cfg: Settings) -> Keypair:
    """The repo keypair if present; otherwise a throwaway in-memory one (nothing written to disk)."""
    if cfg.key_path.exists():
        return ensure_keypair(cfg)
    pub = Ed25519PrivateKey.generate().public_key().public_bytes(
        serialization.Encoding.OpenSSH, serialization.PublicFormat.OpenSSH
    )
    return Keypair(cfg.key_path.resolve(), pub.decode())


# fedlab passes only what it needs: the repo key and non-interactive, no-host-key-check options (the VMs'
# IPs are reused). Everything else (jump hosts, multiplexing, per-host rules) comes from the user's own
# ssh configuration, which fedlab deliberately does not override.
SSH_BASE_OPTS = [
    "-o", "IdentitiesOnly=yes", "-o", "BatchMode=yes", "-o", "StrictHostKeyChecking=no",
    "-o", "UserKnownHostsFile=/dev/null", "-o", "LogLevel=ERROR",
]


def render_ssh_config(cfg: Settings, infos: list[NodeInfo], key: Keypair) -> str:
    lines = ["# Generated by fedlab. Do not edit; rewritten whenever node state changes.", ""]
    for i in infos:
        if not i.public_ip:
            continue
        lines += [
            f"Host {i.name}",
            f"    HostName {i.public_ip}",
            f"    User {cfg.ssh_user}",
            f"    IdentityFile {key.private_path}",
            "    IdentitiesOnly yes",
            "    StrictHostKeyChecking no",
            "    UserKnownHostsFile /dev/null",
            "    LogLevel ERROR",
            "",
        ]
    return "\n".join(lines)


def include_line(cfg: Settings) -> str:
    return f"Include {cfg.ssh_config_path}"


def ssh_include_present(cfg: Settings) -> bool:
    main = Path("~/.ssh/config").expanduser()
    if not main.exists():
        return False
    wanted = {include_line(cfg), f"Include {cfg.ssh_config_path.expanduser()}"}
    return any(line.strip() in wanted for line in main.read_text().splitlines())


def add_ssh_include(cfg: Settings) -> None:
    """Prepend the Include (it must precede any Host block to apply globally)."""
    main = Path("~/.ssh/config").expanduser()
    main.parent.mkdir(mode=0o700, exist_ok=True)
    existing = main.read_text() if main.exists() else ""
    main.write_text(f"{include_line(cfg)}\n\n{existing}")
    main.chmod(0o600)


def write_ssh_config(cfg: Settings, infos: list[NodeInfo], key: Keypair) -> Path:
    path = cfg.ssh_config_path.expanduser()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_ssh_config(cfg, infos, key))
    path.chmod(0o600)
    return path


def write_nodes_json(cfg: Settings, infos: list[NodeInfo], key: Keypair) -> Path:
    roles = {n.name: n.role for n in cfg.resolved_nodes()}
    sites = {n.name: n.site for n in cfg.resolved_nodes()}
    data = {
        i.name: {
            "role": roles.get(i.name),
            "site": sites.get(i.name),
            "provider": i.provider,
            "location": i.location,
            "state": i.state,
            "public_ip": i.public_ip,
            "ssh_user": cfg.ssh_user,
            "ssh_key": str(key.private_path),
            "ports": cfg.ports_for(roles.get(i.name, "client")),
            # The SuperLink's Fleet API is the only Flower port clients reach (server only).
            # The ServerAppIo (9091) and Control (9093) APIs listen on the server's loopback.
            "flower": (
                {"fleet_api": f"{i.public_ip}:9092"}
                if i.public_ip and roles.get(i.name) == "server"
                else None
            ),
        }
        for i in infos
    }
    cfg.nodes_file.parent.mkdir(parents=True, exist_ok=True)
    cfg.nodes_file.write_text(json.dumps(data, indent=2) + "\n")
    return cfg.nodes_file


def probe_ssh(host: str, user: str, key: Keypair, timeout: float = 10) -> tuple[bool, str]:
    """One-shot reachability + auth check: runs `true` over SSH with the repo key. Returns (ok, detail)."""
    cmd = [
        "ssh", "-i", str(key.private_path), *SSH_BASE_OPTS, "-o", f"ConnectTimeout={int(timeout)}", f"{user}@{host}", "true",
    ]
    start = time.monotonic()
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout + 5)
    except subprocess.TimeoutExpired:
        return False, "timed out"
    except FileNotFoundError:
        return False, "`ssh` not found on PATH"
    if r.returncode == 0:
        return True, f"{(time.monotonic() - start) * 1000:.0f} ms"
    return False, (r.stderr.strip().splitlines() or [f"ssh exited {r.returncode}"])[-1]


def wait_for_login(host: str, user: str, key: Keypair, timeout: float = 300, interval: float = 5) -> bool:
    """Wait until an SSH login with the repo key works.

    This runs the real `ssh` program, so it also proves that the key is accepted.
    """
    deadline = time.monotonic() + timeout
    while True:
        if probe_ssh(host, user, key)[0]:
            return True
        if time.monotonic() + interval >= deadline:
            return False
        time.sleep(interval)
